### ISSUE TITLE
Mods creates empty tag problems

### ISSUE THREAD

**Issue by YnwLNE** [MrRedstoneToGo/CreateDecoAdditions#1]
It does fix the zinc issue but breaks the creation of andesite alloy sheets amongst other recipes

**Comment by BugInYourCode01** [comment]
I have tried the datapack on both fabric and forge and it all worked (at least with the andesite alloy sheets).
1. are you forge or fabric?
2. send me one or more screenshots of the problematic recipe(s).
3. if you are playing a modpack, please list all mods.

**Comment by YnwLNE** [comment]
Forge (47.2.21)
modlist pastebin with modpack export included at the bottom. There are unlisted 3rd party mods such as: your mod, particular, memoryleakfix, and tru.e ending 

https://pastebin.com/Vx8uTCV2

Things to note: removing your mod fixes the empty tags but obviously reverts deco's needless changes.
I'd been having an issue with item stacks splitting, which I guess is an NBT problem, so if this doesn't help anything, I hope it at least gives insight or direction. I tried doing a few binary searches but didn't come up with anything.

Here are the screenshots:
![2024-06-20_16 03 59](https://github.com/MrRedstoneToGo/CreateDecoAdditions/assets/81484850/8a4372d0-0162-469b-a9c0-74839d00a20c)
![2024-06-20_16 04 13](https://github.com/MrRedstoneToGo/CreateDecoAdditions/assets/81484850/9c061fa6-aaba-4f23-a266-a34a970b22a0)
![2024-06-20_16 04 27](https://github.com/MrRedstoneToGo/CreateDecoAdditions/assets/81484850/edc83ef3-1ec1-424d-b030-61aee7ad8415)
![2024-06-20_16 06 19](https://github.com/MrRedstoneToGo/CreateDecoAdditions/assets/81484850/49fe0e44-7cd5-43b9-84de-08a80a9fabf5)

**Comment by BugInYourCode01** [comment]
I think I have found the problem:

Firstly, I didn't use the tag forge:gem/source anywhere. Is the item that should come out at the end even from Create Deco?
As far as I'm concerned, brass sheets were tagged as forge:sheets/brass instead of forge:plates/brass. Also, the tag file for forge:ingots/andesite_alloy had no json extension.
I have now changed both and will soon have the files for Modrinth ready. Thanks for your help and let me know if there are any other problems.

**Comment by YnwLNE** [comment]
> I think I have found the problem:
> 
> Firstly, I didn't use the tag forge:gem/source anywhere. Is the item that should come out at the end even from Create Deco? As far as I'm concerned, brass sheets were tagged as forge:sheets/brass instead of forge:plates/brass. Also, the tag file for forge:ingots/andesite_alloy had no json extension. I have now changed both and will soon have the files for Modrinth ready. Thanks for your help and let me know if there are any other problems.

It works! I went through every sheet process and affected recipe and all of them didn't have an empty tag and could now be craftable. All of them were Deco items except a single shield from superior shields, that is the forge:gem/source but that normally isn't craftable due to it being a cross over compat with another mod that is not installed in the pack, Idk why that showed up. This also gave me a bit more insight to my item stack splitting/nbt problem I've been having before deco, crafts, and the compat mod were added to the pack, Thank you!

Your help was greatly appreciated and I am very grateful for your work.

**Comment by YnwLNE** [comment]
Update: for some reason these didn't show at first, but the Industrial Iron Train Hull and Andesite Train Hull, both from Deco, both have empty tags. nothing was changed except for the addition of the update earlier
![image](https://github.com/MrRedstoneToGo/CreateDecoAdditions/assets/81484850/e0e3116b-b16e-4812-bd92-c2e9170fe887)

**Comment by BugInYourCode01** [comment]
fixed
